In [2]:
import pandas as pd

In [4]:
!pip install openpyxl

Collecting openpyxl

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [5]:
df = pd.read_excel("Inside_the_Customer_Journey_Raw_Dataset.xlsx")

In [6]:
df.head()

,Session_ID,Customer_ID,Visit_Date,Age,Gender,City,Customer_Type,Previous_Purchases,Device,Traffic_Source,...,Cart_Value_INR,Discount_Offered,Discount_Percent,Discount_Used,Purchased,Purchase_Amount_INR,Payment_Method,Delivery_Type,Review_Rating,Customer_Satisfaction
0,SES505319,CUST11585,2025-10-31,28,Female,Lucknow,New,1,Desktop,Facebook,...,10537,Yes,10,No,Yes,9447,UPI,Standard,3.0,3.8
1,SES503219,CUST10452,2026-02-14,43,Male,Lucknow,Returning,8,Mobile,Facebook,...,59330,Yes,10,Yes,Yes,36054,Debit Card,Standard,4.4,4.7
2,SES505118,CUST11821,2025-06-29,36,Male,Jaipur,New,0,Desktop,Facebook,...,0,No,0,No,No,0,Debit Card,Same Day,NaN,NaN
3,SES501667,CUST10036,2026-02-24,26,Male,Delhi,New,0,Desktop,Google,...,1504,No,0,No,Yes,1136,Debit Card,Standard,4.1,5.0
4,SES503660,CUST10940,2025-09-24,36,Female,Hyderabad,New,0,Mobile,Email,...,12364,Yes,20,Yes,Yes,11134,Wallet,Express,3.9,4.6

In [7]:
df.shape

(6035, 27)

In [8]:
df.columns

Index(['Session_ID', 'Customer_ID', 'Visit_Date', 'Age', 'Gender', 'City',
       'Customer_Type', 'Previous_Purchases', 'Device', 'Traffic_Source',
       'Session_Duration_Min', 'Pages_Viewed', 'Products_Viewed',
       'Product_Category', 'Item_Purchased', 'Product_Price_INR',
       'Added_to_Cart', 'Cart_Value_INR', 'Discount_Offered',
       'Discount_Percent', 'Discount_Used', 'Purchased', 'Purchase_Amount_INR',
       'Payment_Method', 'Delivery_Type', 'Review_Rating',
       'Customer_Satisfaction'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6035 entries, 0 to 6034
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Session_ID             6035 non-null   object
 1   Customer_ID            6035 non-null   object
 2   Visit_Date             6035 non-null   datetime64[ns]
 3   Age                    6035 non-null   int64
 4   Gender                 5990 non-null   object
 5   City                   6000 non-null   object
 6   Customer_Type          6035 non-null   object
 7   Previous_Purchases     6035 non-null   int64
 8   Device                 6035 non-null   object
 9   Traffic_Source         6005 non-null   object
 10  Session_Duration_Min   6035 non-null   float64
 11  Pages_Viewed           6035 non-null   int64
 12  Products_Viewed        6035 non-null   int64
 13  Product_Category       6035 non-null   object
 14  Item_Purchased         6035 non-null   object
 15  Product_Price_INR      6035 non-null   float64
 16  Added_to_Cart          6035 non-null   object
 17  Cart_Value_INR         6035 non-null   int64
 18  Discount_Offered       6035 non-null   object
 19  Discount_Percent       6035 non-null   int64
 20  Discount_Used          6010 non-null   object
 21  Purchased              6035 non-null   object
 22  Purchase_Amount_INR    6035 non-null   object
 23  Payment_Method         6035 non-null   object
 24  Delivery_Type          6035 non-null   object
 25  Review_Rating          2264 non-null   float64
 26  Customer_Satisfaction  2270 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(6), object(16)
memory usage: 1.2+ MB

In [10]:
df.describe()

,Visit_Date,Age,Previous_Purchases,Session_Duration_Min,Pages_Viewed,Products_Viewed,Product_Price_INR,Cart_Value_INR,Discount_Percent,Review_Rating,Customer_Satisfaction
count,6035,6035.000000,6035.000000,6035.000000,6035.000000,6035.000000,6035.000000,6035.000000,6035.000000,2264.000000,2270.000000
mean,2025-10-06 00:47:57.613918976,31.476222,3.716487,9.657399,6.992378,3.970340,7054.691798,5853.905717,7.151616,3.961528,3.973965
min,2025-01-01 00:00:00,5.000000,0.000000,0.500000,1.000000,1.000000,201.000000,0.000000,0.000000,0.000000,1.300000
25%,2025-05-24 12:00:00,24.000000,0.000000,5.600000,5.000000,3.000000,2015.500000,0.000000,0.000000,3.500000,3.400000
50%,2025-10-07 00:00:00,31.000000,0.000000,8.600000,7.000000,4.000000,4269.000000,0.000000,0.000000,4.000000,4.000000
75%,2026-02-21 00:00:00,38.000000,7.000000,12.700000,9.000000,5.000000,9108.000000,6576.500000,15.000000,4.400000,4.600000
max,2026-06-30 00:00:00,101.000000,15.000000,35.000000,22.000000,12.000000,34906.000000,82556.000000,30.000000,9.000000,5.000000
std,NaN,9.316902,4.899654,5.544659,2.445483,1.726477,7632.306332,11366.566581,8.969863,0.690993,0.726757

In [11]:
df.describe(include='object')

,Session_ID,Customer_ID,Gender,City,Customer_Type,Device,Traffic_Source,Product_Category,Item_Purchased,Added_to_Cart,Discount_Offered,Discount_Used,Purchased,Purchase_Amount_INR,Payment_Method,Delivery_Type
count,6035,6035,5990,6000,6035,6035,6005,6035,6035,6035,6035,6010,6035,6035,6035,6035
unique,6000,2059,8,17,2,3,7,12,30,2,2,2,2,2152,11,3
top,SES502639,CUST10019,Male,Delhi,New,Mobile,Google,Fashion,Kurta,No,No,No,No,0,UPI,Standard
freq,2,11,3253,1029,3438,3895,1516,1435,314,3059,3201,4018,3745,3696,2280,3761

In [12]:
df.isnull().sum()

Session_ID                  0
Customer_ID                 0
Visit_Date                  0
Age                         0
Gender                     45
City                       35
Customer_Type               0
Previous_Purchases          0
Device                      0
Traffic_Source             30
Session_Duration_Min        0
Pages_Viewed                0
Products_Viewed             0
Product_Category            0
Item_Purchased              0
Product_Price_INR           0
Added_to_Cart               0
Cart_Value_INR              0
Discount_Offered            0
Discount_Percent            0
Discount_Used              25
Purchased                   0
Purchase_Amount_INR         0
Payment_Method              0
Delivery_Type               0
Review_Rating            3771
Customer_Satisfaction    3765
dtype: int64

In [13]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage

Session_ID                0.000000
Customer_ID               0.000000
Visit_Date                0.000000
Age                       0.000000
Gender                    0.745650
City                      0.579950
Customer_Type             0.000000
Previous_Purchases        0.000000
Device                    0.000000
Traffic_Source            0.497100
Session_Duration_Min      0.000000
Pages_Viewed              0.000000
Products_Viewed           0.000000
Product_Category          0.000000
Item_Purchased            0.000000
Product_Price_INR         0.000000
Added_to_Cart             0.000000
Cart_Value_INR            0.000000
Discount_Offered          0.000000
Discount_Percent          0.000000
Discount_Used             0.414250
Purchased                 0.000000
Purchase_Amount_INR       0.000000
Payment_Method            0.000000
Delivery_Type             0.000000
Review_Rating            62.485501
Customer_Satisfaction    62.386081
dtype: float64

In [14]:
missing_data = pd.DataFrame({
    'Missing Count': df.isnull().sum(),
    'Missing Percentage': (df.isnull().sum() / len(df)) * 100
})

missing_data

                       Missing Count  Missing Percentage
Session_ID                         0            0.000000
Customer_ID                        0            0.000000
Visit_Date                         0            0.000000
Age                                0            0.000000
Gender                            45            0.745650
City                              35            0.579950
Customer_Type                      0            0.000000
Previous_Purchases                 0            0.000000
Device                             0            0.000000
Traffic_Source                    30            0.497100
Session_Duration_Min               0            0.000000
Pages_Viewed                       0            0.000000
Products_Viewed                    0            0.000000
Product_Category                   0            0.000000
Item_Purchased                     0            0.000000
Product_Price_INR                  0            0.000000
Added_to_Cart                      0            0.000000
Cart_Value_INR                     0            0.000000
Discount_Offered                   0            0.000000
Discount_Percent                   0            0.000000
Discount_Used                     25            0.414250
Purchased                          0            0.000000
Purchase_Amount_INR                0            0.000000
Payment_Method                     0            0.000000
Delivery_Type                      0            0.000000
Review_Rating                   3771           62.485501
Customer_Satisfaction           3765           62.386081

In [15]:
df.duplicated().sum()

np.int64(35)

In [16]:
duplicate_percentage = (df.duplicated().sum() / len(df)) * 100

duplicate_percentage

np.float64(0.579950289975145)

In [17]:
df[df.duplicated()]

,Session_ID,Customer_ID,Visit_Date,Age,Gender,City,Customer_Type,Previous_Purchases,Device,Traffic_Source,...,Cart_Value_INR,Discount_Offered,Discount_Percent,Discount_Used,Purchased,Purchase_Amount_INR,Payment_Method,Delivery_Type,Review_Rating,Customer_Satisfaction
402,SES500222,CUST10338,2025-07-08,34,Female,Lucknow,New,0,Desktop,Google,...,0,Yes,5,Yes,No,0,UPI,Express,NaN,NaN
1179,SES501783,CUST11204,2025-12-02,29,Male,Hyderabad,Returning,10,Desktop,Google,...,4583,No,0,No,Yes,3084,Credit Card,Standard,4.9,4.1
1345,SES500394,CUST10090,2026-06-12,30,Female,Lucknow,Returning,6,Mobile,Facebook,...,0,No,0,No,No,0,UPI,Express,NaN,NaN
1404,SES503708,CUST11535,2025-06-30,36,Female,Pune,Returning,15,Mobile,Referral,...,13422,No,0,No,No,0,Cash on Delivery,Same Day,NaN,NaN
1453,SES505352,CUST11798,2026-06-08,31,Female,Pune,Returning,9,Mobile,Email,...,0,Yes,5,No,Yes,697,UPI,Standard,3.9,4.4
1522,SES502136,CUST12097,2026-04-22,44,Female,Bangalore,New,1,Tablet,Instagram,...,0,No,0,No,No,0,UPI,Standard,NaN,NaN
1577,SES500324,CUST11694,2025-10-15,30,Male,Delhi,Returning,6,Mobile,Google,...,73888,Yes,10,No,Yes,35304,UPI,Standard,3.6,3.5
1659,SES503194,CUST10452,2026-03-10,28,Male,Hyderabad,New,0,Mobile,Email,...,0,Yes,25,Yes,Yes,1030,UPI,Standard,3.7,4.5
1726,SES500168,CUST10294,2026-05-23,29,Female,Chennai,New,0,Mobile,Direct,...,0,No,0,No,No,0,UPI,Same Day,NaN,NaN
2029,SES502188,CUST11106,2025-11-20,41,Female,Mumbai,New,0,Desktop,Google,...,4227,No,0,No,No,0,Net Banking,Same Day,NaN,NaN
2191,SES502339,CUST10968,2026-02-08,18,Female,Chennai,New,1,Mobile,YouTube,...,0,Yes,20,No,No,0,Debit Card,Standard,NaN,NaN
2197,SES505113,CUST11320,2025-11-10,27,Female,Kolkata,New,0,Mobile,YouTube,...,33341,No,0,No,No,0,UPI,Express,NaN,NaN
2558,SES505225,CUST10284,2025-02-25,33,Male,Bangalore,Returning,8,Mobile,Google,...,0,Yes,15,No,No,0,Credit Card,Standard,NaN,NaN
2596,SES504103,CUST11004,2025-03-03,39,Male,Pune,Returning,6,Desktop,YouTube,...,0,Yes,10,Yes,No,0,Net Banking,Standard,NaN,NaN
2864,SES501262,CUST11691,2026-01-26,34,Male,Bangalore,New,0,Mobile,Google,...,0,No,0,No,Yes,5435,Wallet,Standard,3.4,4.9
2887,SES503755,CUST10166,2026-01-17,18,Male,Delhi,New,0,Mobile,YouTube,...,0,No,0,No,No,0,UPI,Standard,NaN,NaN
3094,SES503918,CUST11395,2026-01-26,27,Female,Hyderabad,New,0,Mobile,Direct,...,0,No,0,No,No,0,Cash on Delivery,Standard,NaN,NaN
3524,SES504895,CUST11913,2025-06-09,37,Female,Mumbai,Returning,6,Desktop,Google,...,19382,Yes,5,No,Yes,22589,UPI,Standard,3.1,3.7
3956,SES504007,CUST10192,2026-06-07,25,Male,Delhi,New,0,Mobile,Instagram,...,0,Yes,20,Yes,No,0,Credit Card,Standard,NaN,NaN
4040,SES500320,CUST10269,2025-02-15,37,Female,Delhi,New,0,Desktop,YouTube,...,0,No,0,No,No,0,Cash on Delivery,Standard,NaN,NaN
4075,SES500157,CUST11154,2026-01-25,44,Male,Pune,New,0,Mobile,Google,...,2566,No,0,No,Yes,2838,UPI,Standard,3.6,4.8
4140,SES501658,CUST11444,2025-12-11,42,Female,Delhi,Returning,9,Mobile,Referral,...,0,No,0,No,No,0,Wallet,Same Day,NaN,NaN
4332,SES501169,CUST11869,2026-02-28,18,Male,Chennai,New,0,Mobile,YouTube,...,0,Yes,10,Yes,Yes,16145,UPI,Standard,4.4,3.3
4358,SES505303,CUST11936,2026-03-07,48,Female,Mumbai,New,0,Mobile,Instagram,...,0,Yes,25,Yes,No,0,UPI,Standard,NaN,NaN
4424,SES502639,CUST11440,2026-02-20,39,Male,Kolkata,New,0,Mobile,Direct,...,0,No,0,No,No,0,UPI,Standard,NaN,NaN
4680,SES500747,CUST10724,2025-05-25,29,Female,Lucknow,Returning,9,Tablet,Facebook,...,0,No,0,No,No,0,UPI,Standard,NaN,NaN
4850,SES505757,CUST12157,2026-06-27,28,Female,Mumbai,New,0,Mobile,Referral,...,0,No,0,No,No,0,Wallet,Standard,NaN,NaN
4920,SES500880,CUST10937,2025-12-31,35,Female,Hyderabad,New,0,Desktop,Email,...,6718,No,0,No,No,0,Net Banking,Standard,NaN,NaN
5438,SES501872,CUST12045,2025-10-02,25,Male,Chennai,New,0,Mobile,Instagram,...,0,Yes,20,Yes,No,0,Debit Card,Express,NaN,NaN
5645,SES505626,CUST12199,2025-09-02,27,Male,Ahmedabad,Returning,12,Mobile,Referral,...,9756,Yes,10,No,No,0,Credit Card,Express,NaN,NaN
5675,SES500812,CUST10503,2025-08-17,25,Male,Jaipur,Returning,8,Mobile,YouTube,...,1312,No,0,No,No,0,Wallet,Standard,NaN,NaN
5691,SES502765,CUST11239,2026-04-28,47,Female,Lucknow,New,1,Mobile,Facebook,...,0,No,0,No,No,0,Cash on Delivery,Express,NaN,NaN
5698,SES503594,CUST11241,2025-08-12,19,Male,Lucknow,New,0,Mobile,Referral,...,0,Yes,25,Yes,No,0,UPI,Standard,NaN,NaN
5717,SES502612,CUST11851,2026-06-19,34,Male,Mumbai,Returning,8,Desktop,Facebook,...,0,No,0,No,No,0,Wallet,Standard,NaN,NaN
5781,SES505471,CUST11566,2025-03-19,18,Male,Delhi,New,0,Desktop,Google,...,1808,Yes,10,Yes,No,0,UPI,Express,NaN,NaN

In [18]:
categorical_columns = df.select_dtypes(include='object').columns

categorical_columns

Index(['Session_ID', 'Customer_ID', 'Gender', 'City', 'Customer_Type',
       'Device', 'Traffic_Source', 'Product_Category', 'Item_Purchased',
       'Added_to_Cart', 'Discount_Offered', 'Discount_Used', 'Purchased',
       'Purchase_Amount_INR', 'Payment_Method', 'Delivery_Type'],
      dtype='object')

In [19]:
df.nunique()

Session_ID               6000
Customer_ID              2059
Visit_Date                546
Age                        50
Gender                      8
City                       17
Customer_Type               2
Previous_Purchases         16
Device                      3
Traffic_Source              7
Session_Duration_Min      302
Pages_Viewed               19
Products_Viewed            12
Product_Category           12
Item_Purchased             30
Product_Price_INR        4790
Added_to_Cart               2
Cart_Value_INR           2760
Discount_Offered            2
Discount_Percent            7
Discount_Used               2
Purchased                   2
Purchase_Amount_INR      2152
Payment_Method             11
Delivery_Type               3
Review_Rating              38
Customer_Satisfaction      37
dtype: int64

In [20]:
data_types = pd.DataFrame({
    'Column': df.columns,
    'Data Type': df.dtypes.astype(str).values
})

data_types

                   Column       Data Type
0              Session_ID          object
1             Customer_ID          object
2              Visit_Date  datetime64[ns]
3                     Age           int64
4                  Gender          object
5                    City          object
6           Customer_Type          object
7      Previous_Purchases           int64
8                  Device          object
9          Traffic_Source          object
10   Session_Duration_Min         float64
11           Pages_Viewed           int64
12        Products_Viewed           int64
13       Product_Category          object
14         Item_Purchased          object
15      Product_Price_INR         float64
16          Added_to_Cart          object
17         Cart_Value_INR           int64
18       Discount_Offered          object
19       Discount_Percent           int64
20          Discount_Used          object
21              Purchased          object
22    Purchase_Amount_INR          object
23         Payment_Method          object
24          Delivery_Type          object
25          Review_Rating         float64
26  Customer_Satisfaction         float64

In [21]:
df.isnull().sum()

Session_ID                  0
Customer_ID                 0
Visit_Date                  0
Age                         0
Gender                     45
City                       35
Customer_Type               0
Previous_Purchases          0
Device                      0
Traffic_Source             30
Session_Duration_Min        0
Pages_Viewed                0
Products_Viewed             0
Product_Category            0
Item_Purchased              0
Product_Price_INR           0
Added_to_Cart               0
Cart_Value_INR              0
Discount_Offered            0
Discount_Percent            0
Discount_Used              25
Purchased                   0
Purchase_Amount_INR         0
Payment_Method              0
Delivery_Type               0
Review_Rating            3771
Customer_Satisfaction    3765
dtype: int64

In [22]:
missing_summary = pd.DataFrame({
    'Missing Count': df.isnull().sum(),
    'Missing Percentage': (df.isnull().sum() / len(df) * 100).round(2)
})

missing_summary

                       Missing Count  Missing Percentage
Session_ID                         0                0.00
Customer_ID                        0                0.00
Visit_Date                         0                0.00
Age                                0                0.00
Gender                            45                0.75
City                              35                0.58
Customer_Type                      0                0.00
Previous_Purchases                 0                0.00
Device                             0                0.00
Traffic_Source                    30                0.50
Session_Duration_Min               0                0.00
Pages_Viewed                       0                0.00
Products_Viewed                    0                0.00
Product_Category                   0                0.00
Item_Purchased                     0                0.00
Product_Price_INR                  0                0.00
Added_to_Cart                      0                0.00
Cart_Value_INR                     0                0.00
Discount_Offered                   0                0.00
Discount_Percent                   0                0.00
Discount_Used                     25                0.41
Purchased                          0                0.00
Purchase_Amount_INR                0                0.00
Payment_Method                     0                0.00
Delivery_Type                      0                0.00
Review_Rating                   3771               62.49
Customer_Satisfaction           3765               62.39

In [23]:
pd.crosstab(
    df['Purchased'],
    df['Review_Rating'].isnull(),
    margins=True
)

Review_Rating  False  True   All
Purchased
No                 5  3740  3745
Yes             2259    31  2290
All             2264  3771  6035

In [24]:
pd.crosstab(
    df['Purchased'],
    df['Customer_Satisfaction'].isnull(),
    margins=True
)

Customer_Satisfaction  False  True   All
Purchased
No                         0  3745  3745
Yes                     2270    20  2290
All                     2270  3765  6035

In [26]:
df['Review_Rating'].value_counts(dropna=False).sort_index()

Review_Rating
0.0       2
1.5       2
1.6       1
1.8       1
2.0       3
2.1       3
2.2       9
2.3       6
2.4       8
2.5      18
2.6      15
2.7      17
2.8      34
2.9      46
3.0      42
3.1      67
3.2      59
3.3      76
3.4      98
3.5      92
3.6     110
3.7     117
3.8     124
3.9     143
4.0     129
4.1     123
4.2     113
4.3     119
4.4     131
4.5     106
4.6      80
4.7      75
4.8      59
4.9      61
5.0     167
5.5       4
6.0       1
9.0       3
NaN    3771
Name: count, dtype: int64

In [27]:
df['Customer_Satisfaction'].value_counts(dropna=False).sort_index()

Customer_Satisfaction
1.3       2
1.5       1
1.6       2
1.7       3
1.8       4
1.9       2
2.0       2
2.1       7
2.2       9
2.3       7
2.4      17
2.5      15
2.6      17
2.7      29
2.8      37
2.9      48
3.0      53
3.1      49
3.2      66
3.3     105
3.4      94
3.5      93
3.6      84
3.7     104
3.8     107
3.9     118
4.0     111
4.1      89
4.2     104
4.3     102
4.4     108
4.5     110
4.6      85
4.7      79
4.8      64
4.9      74
5.0     269
NaN    3765
Name: count, dtype: int64

In [28]:
df['Product_Category'].value_counts(dropna=False)

Product_Category
Fashion             1435
Electronics         1228
Beauty               941
Home & Kitchen       881
Books                715
Sports               653
 fashion              47
 electronics          39
 home & kitchen       26
 sports               25
 beauty               24
 books                21
Name: count, dtype: int64

In [29]:
df['Product_Category'] = df['Product_Category'].str.strip().str.title()

In [30]:
df['Product_Category'].value_counts()

Product_Category
Fashion           1482
Electronics       1267
Beauty             965
Home & Kitchen     907
Books              736
Sports             678
Name: count, dtype: int64

In [33]:
df['Gender'].value_counts(dropna=False)

Gender
Male      3253
Female    2523
female      45
NaN         45
FEMALE      44
 F          35
male        35
 M          32
MALE        23
Name: count, dtype: int64

In [35]:
df['Gender'] = df['Gender'].str.strip().str.upper()

In [36]:
df['Gender'] = df['Gender'].replace({
    'M': 'MALE',
    'F': 'FEMALE'
})

In [37]:
df['Gender'].value_counts(dropna=False)

Gender
MALE      3343
FEMALE    2647
NaN         45
Name: count, dtype: int64

In [38]:
df['Gender'] = df['Gender'].fillna('UNKNOWN')

In [39]:
df['Gender'].value_counts()

Gender
MALE       3343
FEMALE     2647
UNKNOWN      45
Name: count, dtype: int64

In [40]:
df['City'].value_counts(dropna=False)

City
Delhi         1029
Mumbai         881
Bangalore      764
Hyderabad      523
Pune           506
Chennai        498
Kolkata        454
Jaipur         425
Ahmedabad      392
Lucknow        286
 delhi          48
 Delhi          37
NaN             35
MUMBAI          35
DELHI           32
 bangalore      32
New Delhi       32
 mumbai         26
Name: count, dtype: int64

In [41]:
df['City'] = df['City'].str.strip().str.title()

In [42]:
df['City'].value_counts(dropna=False)

City
Delhi        1146
Mumbai        942
Bangalore     796
Hyderabad     523
Pune          506
Chennai       498
Kolkata       454
Jaipur        425
Ahmedabad     392
Lucknow       286
NaN            35
New Delhi      32
Name: count, dtype: int64

In [43]:
df['City'] = df['City'].fillna('Unknown')

In [44]:
df['City'].value_counts()

City
Delhi        1146
Mumbai        942
Bangalore     796
Hyderabad     523
Pune          506
Chennai       498
Kolkata       454
Jaipur        425
Ahmedabad     392
Lucknow       286
Unknown        35
New Delhi      32
Name: count, dtype: int64

In [48]:
df['Traffic_Source'].value_counts(dropna=False)

Traffic_Source
Google       1516
Instagram    1076
Direct        993
Facebook      667
Email         619
YouTube       615
Referral      519
NaN            30
Name: count, dtype: int64

In [49]:
df['Traffic_Source'] = df['Traffic_Source'].fillna('Unknown')

In [50]:
df['Traffic_Source'].value_counts()

Traffic_Source
Google       1516
Instagram    1076
Direct        993
Facebook      667
Email         619
YouTube       615
Referral      519
Unknown        30
Name: count, dtype: int64

In [51]:
df['Discount_Used'].value_counts(dropna=False)

Discount_Used
No     4018
Yes    1992
NaN      25
Name: count, dtype: int64

In [52]:
df['Discount_Used'] = df['Discount_Used'].fillna('Unknown')

In [53]:
df['Discount_Used'].value_counts()

Discount_Used
No         4018
Yes        1992
Unknown      25
Name: count, dtype: int64

In [54]:
df[df['Purchased'] == 'Yes'].groupby('Product_Category')['Review_Rating'].median()

Product_Category
Beauty            4.0
Books             4.0
Electronics       4.0
Fashion           4.0
Home & Kitchen    4.0
Sports            3.9
Name: Review_Rating, dtype: float64

In [55]:
df.loc[
    df['Review_Rating'].notna() &
    ((df['Review_Rating'] < 0) | (df['Review_Rating'] > 5)),
    ['Customer_ID', 'Purchased', 'Product_Category', 'Review_Rating']
]

     Customer_ID Purchased Product_Category  Review_Rating
220    CUST11381        No          Fashion            5.5
1411   CUST12146        No   Home & Kitchen            5.5
1661   CUST10443       Yes      Electronics            9.0
2045   CUST10263        No      Electronics            6.0
2203   CUST11896       Yes           Sports            9.0
2416   CUST11858       Yes           Beauty            9.0
2718   CUST11784       Yes           Beauty            5.5
3364   CUST10254        No            Books            5.5

In [58]:
import numpy as np

In [59]:
df.loc[
    df['Review_Rating'] > 5,
    'Review_Rating'
] = np.nan

In [60]:
rating_medians = (
    df.loc[
        (df['Purchased'] == 'Yes') &
        (df['Review_Rating'].notna())
    ]
    .groupby('Product_Category')['Review_Rating']
    .median()
)

rating_medians

Product_Category
Beauty            4.0
Books             4.0
Electronics       4.0
Fashion           4.0
Home & Kitchen    4.0
Sports            3.9
Name: Review_Rating, dtype: float64

In [61]:
df.loc[
    (df['Purchased'] == 'Yes') & (df['Review_Rating'].isna()),
    'Review_Rating'
] = (
    df.loc[
        (df['Purchased'] == 'Yes') & (df['Review_Rating'].isna()),
        'Product_Category'
    ].map(rating_medians)
)

In [62]:
df['Review_Rating'].value_counts(dropna=False).sort_index()

Review_Rating
0.0       2
1.5       2
1.6       1
1.8       1
2.0       3
2.1       3
2.2       9
2.3       6
2.4       8
2.5      18
2.6      15
2.7      17
2.8      34
2.9      46
3.0      42
3.1      67
3.2      59
3.3      76
3.4      98
3.5      92
3.6     110
3.7     117
3.8     124
3.9     147
4.0     160
4.1     123
4.2     113
4.3     119
4.4     131
4.5     106
4.6      80
4.7      75
4.8      59
4.9      61
5.0     167
NaN    3744
Name: count, dtype: int64

In [63]:
satisfaction_medians = (
    df.loc[
        (df['Purchased'] == 'Yes') &
        (df['Customer_Satisfaction'].notna())
    ]
    .groupby('Product_Category')['Customer_Satisfaction']
    .median()
)

satisfaction_medians

Product_Category
Beauty            4.0
Books             4.1
Electronics       4.0
Fashion           4.0
Home & Kitchen    4.0
Sports            4.0
Name: Customer_Satisfaction, dtype: float64

In [64]:
df.loc[
    (df['Purchased'] == 'Yes') & (df['Customer_Satisfaction'].isna()),
    'Customer_Satisfaction'
] = (
    df.loc[
        (df['Purchased'] == 'Yes') & (df['Customer_Satisfaction'].isna()),
        'Product_Category'
    ].map(satisfaction_medians)
)

In [65]:
df['Customer_Satisfaction'].value_counts(dropna=False).sort_index()

Customer_Satisfaction
1.3       2
1.5       1
1.6       2
1.7       3
1.8       4
1.9       2
2.0       2
2.1       7
2.2       9
2.3       7
2.4      17
2.5      15
2.6      17
2.7      29
2.8      37
2.9      48
3.0      53
3.1      49
3.2      66
3.3     105
3.4      94
3.5      93
3.6      84
3.7     104
3.8     107
3.9     118
4.0     130
4.1      90
4.2     104
4.3     102
4.4     108
4.5     110
4.6      85
4.7      79
4.8      64
4.9      74
5.0     269
NaN    3745
Name: count, dtype: int64

In [66]:
df.isnull().sum()

Session_ID                  0
Customer_ID                 0
Visit_Date                  0
Age                         0
Gender                      0
City                        0
Customer_Type               0
Previous_Purchases          0
Device                      0
Traffic_Source              0
Session_Duration_Min        0
Pages_Viewed                0
Products_Viewed             0
Product_Category            0
Item_Purchased              0
Product_Price_INR           0
Added_to_Cart               0
Cart_Value_INR              0
Discount_Offered            0
Discount_Percent            0
Discount_Used               0
Purchased                   0
Purchase_Amount_INR         0
Payment_Method              0
Delivery_Type               0
Review_Rating            3744
Customer_Satisfaction    3745
dtype: int64

In [67]:
df.duplicated().sum()

np.int64(35)

In [68]:
df = df.drop_duplicates().reset_index(drop=True)

In [69]:
df.duplicated().sum()

np.int64(0)

In [70]:
df.shape

(6000, 27)

In [71]:
df.isnull().sum()

Session_ID                  0
Customer_ID                 0
Visit_Date                  0
Age                         0
Gender                      0
City                        0
Customer_Type               0
Previous_Purchases          0
Device                      0
Traffic_Source              0
Session_Duration_Min        0
Pages_Viewed                0
Products_Viewed             0
Product_Category            0
Item_Purchased              0
Product_Price_INR           0
Added_to_Cart               0
Cart_Value_INR              0
Discount_Offered            0
Discount_Percent            0
Discount_Used               0
Purchased                   0
Purchase_Amount_INR         0
Payment_Method              0
Delivery_Type               0
Review_Rating            3717
Customer_Satisfaction    3718
dtype: int64

In [72]:
df['Age'].describe()

count    6000.000000
mean       31.475667
std         9.322852
min         5.000000
25%        24.000000
50%        31.000000
75%        38.000000
max       101.000000
Name: Age, dtype: float64

In [73]:
df['Previous_Purchases'].describe()

count    6000.000000
mean        3.719000
std         4.902385
min         0.000000
25%         0.000000
50%         0.000000
75%         7.000000
max        15.000000
Name: Previous_Purchases, dtype: float64

In [74]:
df['Session_Duration_Min'].describe()

count    6000.000000
mean        9.652967
std         5.548976
min         0.500000
25%         5.600000
50%         8.600000
75%        12.600000
max        35.000000
Name: Session_Duration_Min, dtype: float64

In [75]:
df['Pages_Viewed'].describe()

count    6000.000000
mean        6.992000
std         2.442525
min         1.000000
25%         5.000000
50%         7.000000
75%         9.000000
max        22.000000
Name: Pages_Viewed, dtype: float64

In [76]:
df['Products_Viewed'].describe()

count    6000.000000
mean        3.970000
std         1.726054
min         1.000000
25%         3.000000
50%         4.000000
75%         5.000000
max        12.000000
Name: Products_Viewed, dtype: float64

In [77]:
df['Product_Price_INR'].describe()

count     6000.000000
mean      7056.563167
std       7630.718917
min        201.000000
25%       2020.750000
50%       4273.000000
75%       9105.000000
max      34906.000000
Name: Product_Price_INR, dtype: float64

In [78]:
df['Discount_Percent'].describe()

count    6000.000000
mean        7.157500
std         8.971962
min         0.000000
25%         0.000000
50%         0.000000
75%        15.000000
max        30.000000
Name: Discount_Percent, dtype: float64

In [79]:
df['Purchase_Amount_INR'].describe()

count     6000
unique    2152
top          0
freq      3669
Name: Purchase_Amount_INR, dtype: int64

In [80]:
df['Review_Rating'].describe()

count    2283.000000
mean        3.952212
std         0.658037
min         0.000000
25%         3.500000
50%         4.000000
75%         4.400000
max         5.000000
Name: Review_Rating, dtype: float64

In [81]:
df['Customer_Satisfaction'].describe()

count    2282.000000
mean        3.973620
std         0.724014
min         1.300000
25%         3.500000
50%         4.000000
75%         4.500000
max         5.000000
Name: Customer_Satisfaction, dtype: float64

In [82]:
df.loc[
    (df['Age'] < 13) | (df['Age'] > 80),
    ['Customer_ID', 'Age', 'Customer_Type', 'Purchased']
]

     Customer_ID  Age Customer_Type Purchased
1289   CUST11961    5           New        No
2000   CUST11435    9           New        No
2119   CUST11649    9           New        No
2230   CUST11487    5           New        No
2414   CUST11712    5     Returning        No
3188   CUST10594  101     Returning        No
3730   CUST10301    5           New        No
4279   CUST11641  101           New       Yes
4720   CUST10855    9     Returning        No
4890   CUST10283    9     Returning        No
5294   CUST10491  101     Returning       Yes
5494   CUST10974    5     Returning        No

In [83]:
df['Purchase_Amount_INR'].dtype

dtype('O')

In [84]:
df['Purchase_Amount_INR'].head(20)

0      9447
1     36054
2         0
3      1136
4     11134
5       346
6      3384
7      2865
8      3306
9         0
10        0
11        0
12        0
13     2359
14        0
15     3031
16        0
17    12515
18      283
19    10858
Name: Purchase_Amount_INR, dtype: object

In [85]:
df.loc[
    (df['Age'] < 13) | (df['Age'] > 80),
    ['Customer_ID', 'Age', 'Customer_Type', 'Purchased']
]

     Customer_ID  Age Customer_Type Purchased
1289   CUST11961    5           New        No
2000   CUST11435    9           New        No
2119   CUST11649    9           New        No
2230   CUST11487    5           New        No
2414   CUST11712    5     Returning        No
3188   CUST10594  101     Returning        No
3730   CUST10301    5           New        No
4279   CUST11641  101           New       Yes
4720   CUST10855    9     Returning        No
4890   CUST10283    9     Returning        No
5294   CUST10491  101     Returning       Yes
5494   CUST10974    5     Returning        No

In [86]:
df['Purchase_Amount_INR'] = pd.to_numeric(
    df['Purchase_Amount_INR'],
    errors='coerce'
)

In [87]:
df['Purchase_Amount_INR'].dtype

dtype('float64')

In [88]:
df['Purchase_Amount_INR'].describe()

count     5985.000000
mean      3923.331161
std       8914.890642
min      -4901.000000
25%          0.000000
50%          0.000000
75%       3711.000000
max      68805.000000
Name: Purchase_Amount_INR, dtype: float64

In [89]:
pd.crosstab(
    df['Purchased'],
    df['Purchase_Amount_INR'].eq(0)
)

Purchase_Amount_INR  False  True
Purchased
No                      17   3701
Yes                   2282      0

In [90]:
df['Purchase_Amount_INR'] = pd.to_numeric(
    df['Purchase_Amount_INR'],
    errors='coerce'
)

In [91]:
df['Purchase_Amount_INR'].dtype

dtype('float64')

In [92]:
df['Purchase_Amount_INR'].describe()

count     5985.000000
mean      3923.331161
std       8914.890642
min      -4901.000000
25%          0.000000
50%          0.000000
75%       3711.000000
max      68805.000000
Name: Purchase_Amount_INR, dtype: float64

In [93]:
pd.crosstab(
    df['Purchased'],
    df['Purchase_Amount_INR'].eq(0)
)

Purchase_Amount_INR  False  True
Purchased
No                      17   3701
Yes                   2282      0

In [94]:
df.loc[
    df['Purchase_Amount_INR'] < 0,
    ['Customer_ID', 'Purchased', 'Product_Category',
     'Product_Price_INR', 'Discount_Percent',
     'Cart_Value_INR', 'Purchase_Amount_INR']
]

,Customer_ID,Purchased,Product_Category,Product_Price_INR,Discount_Percent,Cart_Value_INR,Purchase_Amount_INR
722,CUST10863,No,Fashion,3878.0,25,0,-1690.0
2105,CUST11793,No,Fashion,1009.0,0,0,-209.0
2572,CUST10241,No,Books,2228.0,10,0,-3046.0
2579,CUST10227,No,Fashion,2825.0,15,0,-1495.0
2663,CUST11504,Yes,Electronics,1817.0,0,3404,-4529.0
3664,CUST10336,No,Beauty,3635.0,15,0,-1310.0
5956,CUST10955,No,Beauty,792.0,5,0,-3842.0
5985,CUST11283,No,Fashion,5032.0,0,0,-4901.0

In [95]:
df.loc[
    (df['Purchased'] == 'No') &
    (df['Purchase_Amount_INR'] > 0),
    ['Customer_ID', 'Purchased', 'Product_Category',
     'Product_Price_INR', 'Discount_Percent',
     'Cart_Value_INR', 'Purchase_Amount_INR']
]

Empty DataFrame
Columns: [Customer_ID, Purchased, Product_Category, Product_Price_INR, Discount_Percent, Cart_Value_INR, Purchase_Amount_INR]
Index: []

In [97]:
df[df['Purchase_Amount_INR'].isna()][
    ['Customer_ID', 'Purchased', 'Purchase_Amount_INR']
]

     Customer_ID Purchased  Purchase_Amount_INR
236    CUST10116        No                  NaN
648    CUST11036        No                  NaN
1183   CUST10662        No                  NaN
1574   CUST11963       Yes                  NaN
1878   CUST11497        No                  NaN
1956   CUST11357       Yes                  NaN
2495   CUST11205        No                  NaN
2504   CUST11933       Yes                  NaN
2634   CUST10329        No                  NaN
2880   CUST10755        No                  NaN
3405   CUST11642       Yes                  NaN
3993   CUST11434       Yes                  NaN
4021   CUST11756        No                  NaN
4930   CUST11072        No                  NaN
5639   CUST11902        No                  NaN

In [98]:
df.loc[
    df['Purchase_Amount_INR'] < 0,
    'Purchase_Amount_INR'
] = np.nan

In [99]:
df.loc[
    (df['Purchased'] == 'No') &
    (df['Purchase_Amount_INR'] > 0),
    'Purchase_Amount_INR'
] = 0

In [100]:
df.loc[
    df['Purchase_Amount_INR'].isna(),
    'Purchased'
].value_counts()

Purchased
No     17
Yes     6
Name: count, dtype: int64

In [101]:
df.loc[
    (df['Purchased'] == 'Yes') &
    (df['Purchase_Amount_INR'].isna()),
    [
        'Customer_ID',
        'Product_Category',
        'Product_Price_INR',
        'Discount_Offered',
        'Discount_Percent',
        'Discount_Used',
        'Cart_Value_INR',
        'Purchased',
        'Purchase_Amount_INR'
    ]
]

,Customer_ID,Product_Category,Product_Price_INR,Discount_Offered,Discount_Percent,Discount_Used,Cart_Value_INR,Purchased,Purchase_Amount_INR
1574,CUST11963,Electronics,22877.0,No,0,No,39395,Yes,NaN
1956,CUST11357,Books,1895.0,No,0,No,3345,Yes,NaN
2504,CUST11933,Sports,11218.0,Yes,5,Yes,16549,Yes,NaN
2663,CUST11504,Electronics,1817.0,No,0,No,3404,Yes,NaN
3405,CUST11642,Books,1271.0,Yes,15,Yes,2486,Yes,NaN
3993,CUST11434,Sports,2239.0,Yes,10,Yes,4308,Yes,NaN

In [102]:
df['Purchase_Amount_INR'].describe()

count     5977.000000
mean      3932.099548
std       8917.441439
min          0.000000
25%          0.000000
50%          0.000000
75%       3715.000000
max      68805.000000
Name: Purchase_Amount_INR, dtype: float64

In [103]:
df.loc[
    df['Purchase_Amount_INR'].isna(),
    ['Customer_ID', 'Purchased', 'Purchase_Amount_INR']
]

     Customer_ID Purchased  Purchase_Amount_INR
236    CUST10116        No                  NaN
648    CUST11036        No                  NaN
722    CUST10863        No                  NaN
1183   CUST10662        No                  NaN
1574   CUST11963       Yes                  NaN
1878   CUST11497        No                  NaN
1956   CUST11357       Yes                  NaN
2105   CUST11793        No                  NaN
2495   CUST11205        No                  NaN
2504   CUST11933       Yes                  NaN
2572   CUST10241        No                  NaN
2579   CUST10227        No                  NaN
2634   CUST10329        No                  NaN
2663   CUST11504       Yes                  NaN
2880   CUST10755        No                  NaN
3405   CUST11642       Yes                  NaN
3664   CUST10336        No                  NaN
3993   CUST11434       Yes                  NaN
4021   CUST11756        No                  NaN
4930   CUST11072        No                  NaN
5639   CUST11902        No                  NaN
5956   CUST10955        No                  NaN
5985   CUST11283        No                  NaN

In [104]:
df.loc[
    (df['Purchased'] == 'No') &
    (df['Purchase_Amount_INR'].isna()),
    'Purchase_Amount_INR'
] = 0

In [105]:
df.isnull().sum()

Session_ID                  0
Customer_ID                 0
Visit_Date                  0
Age                         0
Gender                      0
City                        0
Customer_Type               0
Previous_Purchases          0
Device                      0
Traffic_Source              0
Session_Duration_Min        0
Pages_Viewed                0
Products_Viewed             0
Product_Category            0
Item_Purchased              0
Product_Price_INR           0
Added_to_Cart               0
Cart_Value_INR              0
Discount_Offered            0
Discount_Percent            0
Discount_Used               0
Purchased                   0
Purchase_Amount_INR         6
Payment_Method              0
Delivery_Type               0
Review_Rating            3717
Customer_Satisfaction    3718
dtype: int64

In [106]:
df.loc[
    (df['Age'] < 13) | (df['Age'] > 80),
    ['Customer_ID', 'Age', 'Customer_Type', 'Purchased']
]

     Customer_ID  Age Customer_Type Purchased
1289   CUST11961    5           New        No
2000   CUST11435    9           New        No
2119   CUST11649    9           New        No
2230   CUST11487    5           New        No
2414   CUST11712    5     Returning        No
3188   CUST10594  101     Returning        No
3730   CUST10301    5           New        No
4279   CUST11641  101           New       Yes
4720   CUST10855    9     Returning        No
4890   CUST10283    9     Returning        No
5294   CUST10491  101     Returning       Yes
5494   CUST10974    5     Returning        No

In [107]:
df.loc[
    (df['Age'] < 13) | (df['Age'] > 80),
    'Age'
] = np.nan

In [108]:
df['Age'].describe()

count    5988.000000
mean       31.477956
std         9.151218
min        18.000000
25%        24.000000
50%        31.000000
75%        38.000000
max        65.000000
Name: Age, dtype: float64

In [109]:
df['Age'].isnull().sum()

np.int64(12)

In [112]:
df.shape

(6000, 27)

In [113]:
df.duplicated().sum()

np.int64(0)

In [114]:
df.isnull().sum()

Session_ID                  0
Customer_ID                 0
Visit_Date                  0
Age                        12
Gender                      0
City                        0
Customer_Type               0
Previous_Purchases          0
Device                      0
Traffic_Source              0
Session_Duration_Min        0
Pages_Viewed                0
Products_Viewed             0
Product_Category            0
Item_Purchased              0
Product_Price_INR           0
Added_to_Cart               0
Cart_Value_INR              0
Discount_Offered            0
Discount_Percent            0
Discount_Used               0
Purchased                   0
Purchase_Amount_INR         6
Payment_Method              0
Delivery_Type               0
Review_Rating            3717
Customer_Satisfaction    3718
dtype: int64

In [115]:
df.dtypes

Session_ID                       object
Customer_ID                      object
Visit_Date               datetime64[ns]
Age                             float64
Gender                           object
City                             object
Customer_Type                    object
Previous_Purchases                int64
Device                           object
Traffic_Source                   object
Session_Duration_Min            float64
Pages_Viewed                      int64
Products_Viewed                   int64
Product_Category                 object
Item_Purchased                   object
Product_Price_INR               float64
Added_to_Cart                    object
Cart_Value_INR                    int64
Discount_Offered                 object
Discount_Percent                  int64
Discount_Used                    object
Purchased                        object
Purchase_Amount_INR             float64
Payment_Method                   object
Delivery_Type                    object
Review_Rating                   float64
Customer_Satisfaction           float64
dtype: object

In [116]:
df.dtypes

Session_ID                       object
Customer_ID                      object
Visit_Date               datetime64[ns]
Age                             float64
Gender                           object
City                             object
Customer_Type                    object
Previous_Purchases                int64
Device                           object
Traffic_Source                   object
Session_Duration_Min            float64
Pages_Viewed                      int64
Products_Viewed                   int64
Product_Category                 object
Item_Purchased                   object
Product_Price_INR               float64
Added_to_Cart                    object
Cart_Value_INR                    int64
Discount_Offered                 object
Discount_Percent                  int64
Discount_Used                    object
Purchased                        object
Purchase_Amount_INR             float64
Payment_Method                   object
Delivery_Type                    object
Review_Rating                   float64
Customer_Satisfaction           float64
dtype: object

In [117]:
print("FINAL DATASET VALIDATION")
print("------------------------")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Duplicate Rows:", df.duplicated().sum())
print("Total Missing Values:", df.isnull().sum().sum())
print("Age Range:", df['Age'].min(), "to", df['Age'].max())
print("Purchase Amount Min:", df['Purchase_Amount_INR'].min())

FINAL DATASET VALIDATION
------------------------
Rows: 6000
Columns: 27
Duplicate Rows: 0
Total Missing Values: 7453
Age Range: 18.0 to 65.0
Purchase Amount Min: 0.0

In [118]:
df.to_excel(
    'cleaned_ecommerce_customer_data.xlsx',
    index=False
)

In [119]:
import os

os.path.exists('cleaned_ecommerce_customer_data.xlsx')

True

In [120]:
os.getcwd()

'C:\\Users\\hp\\OneDrive\\Desktop\\Inside Customer Journey'